#!/usr/bin/env bash
#
# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This script wraps GN with a --script-executable pointing at the Dart binary
# packaged with the Flutter tree.
readonly base_dir="$(dirname "$0")"
readonly flutter_dir="$("$base_dir/flutter_location")"
readonly flutter_bin_dir="$flutter_dir/bin"
readonly dart_bin_dir="$flutter_bin_dir/cache/dart-sdk/bin"
# Ensure that the Dart SDK has been downloaded.
if [[ ! -e $dart_bin_dir ]]; then
  "$flutter_bin_dir/flutter" precache
fi
exec gn --script-executable="$dart_bin_dir/dart" $@
