#!/usr/bin/env bash
#
# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Takes the name of a tool in dart_tools/bin (without the .dart extension),
# as well as any parameters to that tool, then runs it with those parameters
# using the version of Dart from the Flutter tree.

readonly base_dir="$(dirname "$0")"
readonly flutter_dir="$("${base_dir}/flutter_location")"
readonly flutter_bin_dir="${flutter_dir}/bin"
readonly dart_bin_dir="${flutter_bin_dir}/cache/dart-sdk/bin"

# Ensure that the Dart SDK has been downloaded.
if [[ ! -e ${dart_bin_dir} ]]; then
  "${flutter_bin_dir}/flutter" precache
fi

readonly tool_script="${base_dir}/dart_tools/bin/$1.dart"
exec "${dart_bin_dir}/dart" "${tool_script}" "${@:2}"
